### PR TITLE
Adding custom button commands for buttons other than lock.

### PR DESCRIPTION
**Pull request by SuchithSridhar**
The config file should allow custom commands for the rest of the buttons since you'd usually want to lock your computer when you suspend or hibernate.

### CODE REVIEW

**Comment by alourie** [comment]
@erikdubois I wonder if we could make it *always* lock prior to suspending or hibernating. It's possible to imagine a scenario when you wouldn't want that, but I bet many want their computer to be locked when they're having a break, or _manually_ suspend it (to preserve a battery I presume).

It's a simple change and I'd do it myself, but I really don't want to have it gone during the next update ;-)

**Comment by SuchithSridhar** [comment]
@[alourie](https://github.com/alourie) in-case you still want a solution for this: https://suchicodes.com/resources/blog/d9a85387-dc90-44f6-b5b9-922f655fc86b#add-hooks-to-actions -- These hooks are really useful for suspend and hibernate. However, I do think this should be included in the archlinux-logout config as well since that would be local and easier.

**Comment by erikdubois** [comment]
added it into dev for now

this will solve the locking for sleep and hibernate

https://youtu.be/thyXSBtcV54

**Review by arcolinuxz — COMMENTED** [review]
already added to the code

**Review by arcolinuxz — COMMENTED** [review]
lets not add this one

**Comment by SuchithSridhar** [comment]
Closing pull request since code has already been included.

**Pull request closed without merging**
